config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :links do 
    member do 
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end  
  end
  devise_for :users
  root "links#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :user
 belongs_to :link
end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_votable
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.link.build
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @comment.user_id = current_user.id
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:peer_comment, :user_id,:link_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!,except:[:index]
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
    @comment= Comment.new({link_id: @link.id})
  end

  # GET /links/new
  def new
    @link = current_user.links.build()
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to links_path
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_from current_user
    redirect_to links_path
  end    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :peer_comment %>
    <%= form.text_field :peer_comment, id: :comment_peer_comment %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table border="2">
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.peer_comment %></td>
        <td><%= comment.user.email %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if !(@comments.pluck(:user_id).include?(current_user.id))%>
    <%= link_to 'New Comment', new_comment_path %>
<%end%>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.peer_comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', links_path%>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <img src="http://scp-wiki.wdfiles.com/local--files/church-of-the-broken-god-hub/SPChu.png" style="width:30px;height:30px" alt="SPChu.png" class="image">   
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="btn btn-primary" href="#">Home</a>
      </li>
      <%if(user_signed_in?)%>
        <!--if the user is signed in then the acc settings,logout-->
        <li class="nav-item active">
          <a class="nav-link" href="/users/sign_out"><%=link_to "signout",destroy_user_session_path,method: :delete%></a>
        </li>
        <li class="nav-item active">
          <a class="btn btn-primary" href="/users/edit">Accountsettings</a>
        </li>
        <li class="nav-item active">
          <a class="btn btn-primary" href="/links">Links</a>
        </li>
        <li class="nav-item active">
          <a class="btn btn-default" href="#">Welcome!<%=current_user.email%></a>
        </li>  
      <%else%>
        <li class="nav-item active">
          <a class="btn btn-primary" href="/users/sign_in">Sign in</a>
          <a class="btn btn-primary" href="/users/sign_up">new Register</a>
        </li>     
      <%end%>
    </ul>
  </div>
</nav>


<!--trails-->
<!-- this is for drop down -->
<!-- <div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Drop down
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>  </head>
    <p class="notice"><%= notice %></p>
  <body>
     <%= render "layouts/nav"%>
     <% if(user_signed_in?)%>
     <% else%>
     <% end%>
    <%= yield %>

  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true, id: "new_link_form") do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">    
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, id: :link_title,class: "form-control" %>
            <span id="titleError"></span>
          </div>

          <div class="form-group">
            <%= form.label :url %>
            <%= form.text_field :url, id: :link_url,class: "form-control" %>
            <span id="urlError"></span>
          </div>

          <div class="form-group">
             <button type="submit" class="btn btn-primary" id="submit_details">Submit</button>
          </div>
          <%= link_to 'Back', links_path %>
      </div>
    </div>
  </div>
<% end %>
<script>
  var titleHandle = document.getElementById("link_title");
  var urlRegex = (/(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/g);
  var urlHandle = document.getElementById('link_url');
  var titleErrorHandle = document.getElementById('titleError');
  var urlErrorHandle = document.getElementById('urlError');
  var validator={
    urlValid: false,
    titleValid: false
  }
  var formHandle = document.getElementById('new_link_form');
  var submitHandle = document.getElementById('submit_details');


  titleHandle.addEventListener('blur',function(){
       if(titleHandle.value === ""){
           titleErrorHandle.innerHTML="the title can't be blank";
           $('#link_title').addClass('form-control is-invalid')
           validator.titleValid = false;
       }
       else{
          titleErrorHandle.innerHTML = "✓";
           $('#link_title').removeClass('form-control is-invalid');
           $('#link_title').addClass('form-control is-valid');
          validator.titleValid = true;
       }
  },false)
  
  urlHandle.addEventListener('blur',function(){
     if(urlHandle.value === ""){
        urlErrorHandle.innerHTML = "this cant be left bland";
        $('#link_url').addClass('form-control is-invalid');
        validator.urlValid = false;
     }
     else{
        if(urlRegex.test(urlHandle.value)=== true){
           urlErrorHandle.innerHTML = "this is a valid url";
           $('#link_url').removeClass('form-control is-invalid')
           $('#link_url').addClass('form-control is-valid')
           validator.urlValid = true;
        }
        else{
           urlErrorHandle.innerHTML = "this is  a invalid url";
           $('#link_url').addClass('form-control is-invalid')
           validator.urlValid = false;
        }
     }
  },false)
  
  formHandle.addEventListener('submit',function(e){
    if(Object.values(validator).includes(false)){
      e.preventDefault();
      setTimeout(function(){
         submitHandle.disabled = false;
      },100)
    }
  },false) 
  
</script>  

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container"> 
<div class = "row"> 
<div class="col-md-6">
<h1>Links</h1>  
<table class="table" border="2">
      <thead>
        <tr>
          <th width="10"><strong>Title</strong></th>
          <th><strong>Url</strong></th>
          <th><strong>Comment</strong></th>
        </tr>
      </thead>
      
      <tbody>
        <%@links.each do |link|%>
            <tr>
                <td><%=link_to link.title,link_path(link.id)%></td>
                <td><%=link_to link.url.truncate(20),"#{link.url}" %></td>
                <td><%=link_to "Upvote",like_link_path(link),method: :put%><%=link.get_upvotes.size%>||
                  <%=link_to "Downvote",dislike_link_path(link),method: :put%><%=link.get_downvotes.size%>
                </td>
            </tr>
        <%end%>
      </tbody>
</table>
</div>
</div>    
</div>
<br/>
<%=link_to "Add A New Link",new_link_path%>

app/views/links/new.html.erb
<%= render 'form', link: @link %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>URL:</strong>
  <%= @link.url %>
</p>
<%if(current_user.id === @link.user.id)%>
	<%= link_to 'Edit', edit_link_path(@link) %> |
	<%= link_to 'Back', links_path %>
<%end%>
Comments are: <%if(@link.comments.size>0)%>
               <ol>
	               <%@link.comments.each do |comment|%>
	                 <li><%=comment.peer_comment%>------<%=comment.user.email%>
	                 <%if(current_user.id === comment.user.id)%>
	                      <%= link_to '--->Edit', edit_comment_path(comment) %>
	                 <%end%>
	                 </li>    
	               <%end%>
               </ol>
             <%else%>
                 <li>There are no comments added and be the first to add</li>
             <%end%>


<!-- thsi is for the form -->
<%if !(@link.comments.pluck(:user_id).include?(current_user.id))%>
Add a Comment
<%= form_for(@comment) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :peer_comment %>
    <%= form.text_field :peer_comment, id: :comment_peer_comment %>
  </div>
  <%= form.hidden_field :link_id,value: current_user.id%>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%else%>
<%end%>